// A short caption written back onto a Strava activity after the dashboard
// has numbers for it.
//
// The sync is otherwise read-only. This is the one write: append (or refresh)
// a fenced block at the end of the athlete's own description so the feed
// shows what the run did to fitness, fatigue, form, and the marathon
// projection. The fence is how a later pass finds the block and replaces it
// instead of stacking a second copy. Tagged `excuse:` / `note:` lines live
// above the fence and are left alone.
//
// Attribution includes a URL because that's the point of the line. Strava has
// been known to 400 a description that looks like it contains a link; the
// caller retries once with a URL-free attribution rather than leaving the
// run uncaptioned.

import { addDays, toDayKey } from "./dates.js";
import { predictRace } from "./predict.js";
import { median } from "./stats.js";

export const ATTRIBUTION = "Generated by https://maxeisen.me/training";
export const ATTRIBUTION_PLAIN = "Generated by the training dashboard";
export const CAPTION_WINDOW_DAYS = 3;
export const CAPTION_BUDGET = 2;

const FENCE_START = "──";
const FENCE_END = "──";
// Optional " training" so a block written by the first version is still
// found and replaced rather than stacked under a second fence. Strava
// stores descriptions with CRLF; we normalise before matching.
const FENCE_RE = /\n*──(?: training)?\n[\s\S]*?\n──\s*$/;
const ATTRIBUTION_RE =
	/Generated by (?:https:\/\/)?maxeisen\.me\/training|Generated by the training dashboard/;

function normalizeDescription(description) {
	return String(description || "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

const pad = (n) => String(n).padStart(2, "0");

function signed(value, digits = 1) {
	if (!Number.isFinite(value)) return null;
	const rounded = Number(value.toFixed(digits));
	const magnitude = Math.abs(rounded).toFixed(digits);
	if (rounded > 0) return `+${magnitude}`;
	return rounded < 0 ? `-${magnitude}` : magnitude;
}

function clock(sec) {
	if (!(sec > 0)) return null;
	const total = Math.round(sec);
	const h = Math.floor(total / 3600);
	const m = Math.floor((total % 3600) / 60);
	const s = total % 60;
	return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

function formAt(series, date) {
	const idx = (series || []).findIndex((d) => d.date === date);
	if (idx < 1) return null;
	const before = series[idx - 1];
	const after = series[idx];
	return {
		ctl: after.ctl,
		ctlDelta: after.ctl - before.ctl,
		atl: after.atl,
		atlDelta: after.atl - before.atl,
		tsb: after.tsb,
		tsbDelta: after.tsb - before.tsb,
		dayLoad: after.load,
	};
}

function vsTypicalPct(run, records) {
	const date = toDayKey(run?.startDateLocal);
	if (!date || !(Number(run?.load) > 0)) return null;
	const from = addDays(date, -42);
	const previous = (records || []).filter((other) => {
		if (other === run || String(other?.id) === String(run?.id)) return false;
		if (other?.sport === "ride") return false;
		const day = toDayKey(other?.startDateLocal);
		return day && day >= from && day <= date && Number(other.load) > 0;
	});
	const typical = median(previous.map((r) => Number(r.load)));
	return typical > 0 ? (Number(run.load) / typical) * 100 : null;
}

/**
 * Seconds today's (or this day's) efforts moved the headline prediction.
 *
 * Zero when they didn't beat the existing 5k+ basis. Null when there is
 * no prediction at all.
 *
 * @param {object[]} efforts from collectBestEfforts().
 * @param {string} date day key of the run being captioned.
 * @param {number} targetDistanceM
 * @returns {number|null}
 */
export function sessionDeltaSec(efforts, date, targetDistanceM) {
	const after = predictRace(efforts, targetDistanceM);
	if (!after) return null;
	const prior = predictRace(
		(efforts || []).filter((effort) => effort?.date !== date),
		targetDistanceM,
	);
	if (!prior) return 0;
	return Math.round(after.predictedSec - prior.predictedSec);
}

/**
 * @param {object} metrics
 * @returns {string[]}
 */
export function formatCaptionLines({
	ctl,
	ctlDelta,
	atl,
	atlDelta,
	tsb,
	tsbDelta,
	load,
	vsTypicalPct: typicalPct,
	predictedSec,
	sessionDeltaSec: delta,
} = {}) {
	const lines = [];
	const fitnessDelta = signed(ctlDelta);
	const fatigueDelta = signed(atlDelta);
	const formDelta = signed(tsbDelta);
	if (fitnessDelta) {
		lines.push(`Fitness  ${fitnessDelta}${Number.isFinite(ctl) ? `  →  ${ctl.toFixed(1)}` : ""}`);
	}
	if (fatigueDelta) {
		lines.push(`Fatigue  ${fatigueDelta}${Number.isFinite(atl) ? `  →  ${atl.toFixed(1)}` : ""}`);
	}
	if (formDelta) {
		lines.push(`Form     ${formDelta}${Number.isFinite(tsb) ? `  →  ${tsb.toFixed(1)}` : ""}`);
	}

	if (Number.isFinite(load) && load > 0) {
		const typical =
			Number.isFinite(typicalPct) ? `  ·  ${Math.round(typicalPct)}% of typical` : "";
		lines.push(`Load     ${Math.round(load)}${typical}`);
	}

	const finish = clock(predictedSec);
	if (finish) {
		let move = "no change";
		if (Number.isFinite(delta) && delta !== 0) {
			const faster = delta < 0;
			move = `${clock(Math.abs(delta))} ${faster ? "faster" : "slower"}`;
		}
		lines.push(`Projected  ${finish}  ·  ${move}`);
	}
	return lines;
}

export function hasCaption(description) {
	return ATTRIBUTION_RE.test(normalizeDescription(description));
}

/**
 * Put the caption block at the end of a description, replacing a previous
 * copy of itself if one is already there.
 *
 * @param {string} description
 * @param {string[]} lines from formatCaptionLines().
 * @param {{attribution?: string}} [options]
 * @returns {string}
 */
export function applyCaption(description, lines, { attribution = ATTRIBUTION } = {}) {
	const block = [FENCE_START, ...(lines || []), attribution, FENCE_END].join("\n");
	const stripped = normalizeDescription(description).replace(FENCE_RE, "").trimEnd();
	return stripped ? `${stripped}\n\n${block}` : block;
}

/**
 * Caption recent runs that don't have a stamp yet.
 *
 * Mutates records in place (`captionedAt`). One PUT per run, and a retry
 * without the URL if Strava rejects the description.
 *
 * @param {object} input
 * @returns {Promise<{captioned: number, urlRejected: boolean}>}
 */
export async function captionRecentRuns({
	records = [],
	today,
	series = [],
	efforts = [],
	raceDistanceM = 42195,
	getDescription,
	putDescription,
	deadline = Infinity,
} = {}) {
	const from = addDays(today, -CAPTION_WINDOW_DAYS);
	const candidates = (records || [])
		.filter((a) => {
			if (!a || a.sport === "ride" || a.captionedAt) return false;
			const day = toDayKey(a.startDateLocal);
			return day && day >= from;
		})
		.sort((a, b) => String(b.startDateLocal).localeCompare(String(a.startDateLocal)))
		.slice(0, CAPTION_BUDGET);

	let captioned = 0;
	let urlRejected = false;

	for (const record of candidates) {
		if (Date.now() > deadline) break;
		const date = toDayKey(record.startDateLocal);
		const form = formAt(series, date);
		const predicted = predictRace(efforts, raceDistanceM);
		const lines = formatCaptionLines({
			...form,
			load: record.load,
			vsTypicalPct: vsTypicalPct(record, records),
			predictedSec: predicted?.predictedSec ?? null,
			sessionDeltaSec: sessionDeltaSec(efforts, date, raceDistanceM),
		});
		if (lines.length === 0) continue;

		let description;
		try {
			description = await getDescription(record.id);
		} catch (err) {
			if (err?.status === 429) break;
			console.error(`Failed to read description on ${record.id}`, err);
			continue;
		}

		if (typeof description !== "string") description = "";
		// The attribution line is the lock. If it's already on the activity,
		// a later pass must not write another copy — even when the blob stamp
		// was lost, the fence changed, or Strava stored CRLF.
		if (hasCaption(description)) {
			record.captionedAt = new Date().toISOString();
			captioned += 1;
			continue;
		}

		const withUrl = applyCaption(description, lines);
		try {
			await putDescription(record.id, withUrl);
			record.captionedAt = new Date().toISOString();
			captioned += 1;
		} catch (err) {
			if (err?.status === 429) break;
			if (err?.status === 400) {
				urlRejected = true;
				const withoutUrl = applyCaption(description, lines, {
					attribution: ATTRIBUTION_PLAIN,
				});
				try {
					await putDescription(record.id, withoutUrl);
					record.captionedAt = new Date().toISOString();
					captioned += 1;
				} catch (retryErr) {
					console.error(`Failed to caption ${record.id} without URL`, retryErr);
					if (retryErr?.status === 429) break;
				}
			} else {
				console.error(`Failed to caption ${record.id}`, err);
			}
		}
	}

	return { captioned, urlRejected };
}
