import { describe, it, expect } from "vitest";
import { mergeActivities } from "./store.js";
import { predictRace } from "./predict.js";
import {
	ATTRIBUTION,
	applyCaption,
	captionRecentRuns,
	formatCaptionLines,
	hasCaption,
	sessionDeltaSec,
} from "./caption.js";

describe("applyCaption", () => {
	it("appends a fenced block to a description the athlete wrote", () => {
		const out = applyCaption("felt easy\nexcuse: heat", ["Fitness  +0.3"]);
		expect(out).toContain("felt easy");
		expect(out).toContain("excuse: heat");
		expect(out).toContain("Fitness  +0.3");
		expect(out).toContain(ATTRIBUTION);
		expect(out).toMatch(/Generated by https:\/\/maxeisen\.me\/training/);
		expect(out).not.toContain("── training");
	});

	it("replaces an existing block rather than stacking a second copy", () => {
		const once = applyCaption("felt easy", ["Fitness  +0.3"]);
		const twice = applyCaption(once, ["Fitness  +0.4"]);
		expect(twice.match(/Generated by https:\/\/maxeisen\.me\/training/g)).toHaveLength(1);
		expect(twice).toContain("Fitness  +0.4");
		expect(twice).not.toContain("Fitness  +0.3");
		expect(twice).not.toContain("── training");
		expect(twice).toContain("felt easy");
	});

	it("replaces a block fenced with the old training label", () => {
		const legacy =
			"felt easy\n\n── training\nFitness  +0.3\nGenerated by maxeisen.me/training\n──";
		const out = applyCaption(legacy, ["Fitness  +0.4"]);
		expect(out).not.toContain("── training");
		expect(out).toContain("Fitness  +0.4");
		expect(out).not.toContain("Fitness  +0.3");
	});

	it("still finds the fence when Strava stores CRLF line endings", () => {
		const crlf =
			"felt easy\r\n\r\n── training\r\nFitness  +0.3\r\nGenerated by maxeisen.me/training\r\n──";
		const out = applyCaption(crlf, ["Fitness  +0.4"]);
		expect(out).not.toContain("── training");
		expect(out.match(/Generated by https:\/\/maxeisen\.me\/training/g)).toHaveLength(1);
		expect(out).toContain("felt easy");
	});

	it("writes onto an empty description", () => {
		const out = applyCaption("", ["Form  -1.2"]);
		expect(hasCaption(out)).toBe(true);
		expect(out).toContain("Form  -1.2");
	});

	it("can omit the URL attribution after Strava rejects it", () => {
		const out = applyCaption("ok", ["Load  40"], { attribution: "Generated by the training dashboard" });
		expect(out).not.toMatch(/maxeisen\.me\/training/);
		expect(out).toContain("Generated by the training dashboard");
	});
});

describe("formatCaptionLines", () => {
	it("prints FFF with the day's deltas, load against typical, and an unchanged projection", () => {
		const lines = formatCaptionLines({
			ctl: 42.14,
			ctlDelta: 0.32,
			atl: 48.3,
			atlDelta: 4.11,
			tsb: -6.16,
			tsbDelta: -3.9,
			load: 86,
			vsTypicalPct: 112.4,
			predictedSec: 13200,
			sessionDeltaSec: 0,
		});
		expect(lines[0]).toMatch(/Fitness\s+\+0\.3/);
		expect(lines[1]).toMatch(/Fatigue\s+\+4\.1/);
		expect(lines[2]).toMatch(/Form\s+-3\.9/);
		expect(lines.some((l) => /Load\s+86/.test(l) && /112%/.test(l))).toBe(true);
		expect(lines.some((l) => /Projected/.test(l) && /no change/.test(l) && /3:40:00/.test(l))).toBe(
			true,
		);
	});

	it("says how much today's effort moved the projection when it did", () => {
		const lines = formatCaptionLines({
			ctl: 40,
			ctlDelta: 0.2,
			atl: 50,
			atlDelta: 5,
			tsb: -10,
			tsbDelta: -4,
			load: 90,
			vsTypicalPct: 100,
			predictedSec: 13110,
			sessionDeltaSec: -90,
		});
		expect(lines.find((l) => l.startsWith("Projected"))).toMatch(/1:30 faster/);
	});
});

describe("sessionDeltaSec", () => {
	const marathon = 42195;
	const prior = [{ date: "2026-05-10", distanceM: 10000, timeSec: 2580, name: "10K" }];

	it("is zero when today's 8k does not beat the existing basis", () => {
		const efforts = [...prior, { date: "2026-08-21", distanceM: 8000, timeSec: 2800, name: "8k" }];
		expect(sessionDeltaSec(efforts, "2026-08-21", marathon)).toBe(0);
		expect(predictRace(efforts, marathon).predictedSec).toBe(
			predictRace(prior, marathon).predictedSec,
		);
	});
});

describe("captionRecentRuns", () => {
	const today = "2026-08-21";
	const run = {
		id: 42,
		sport: "run",
		startDateLocal: "2026-08-21T07:00:00",
		load: 50,
	};
	const series = [
		{ date: "2026-08-20", ctl: 40, atl: 44, tsb: -4, load: 80 },
		{ date: "2026-08-21", ctl: 40.3, atl: 48, tsb: -7.7, load: 50 },
	];
	const efforts = [{ date: "2026-05-10", distanceM: 10000, timeSec: 2580, name: "10K" }];

	it("writes once and stamps the record so a later pass is a no-op", async () => {
		const puts = [];
		const records = [{ ...run }];
		const first = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () => "felt easy",
			putDescription: async (id, description) => {
				puts.push({ id, description });
			},
		});
		expect(first.captioned).toBe(1);
		expect(puts).toHaveLength(1);
		expect(puts[0].description).toContain("felt easy");
		expect(puts[0].description).toContain(ATTRIBUTION);
		expect(records[0].captionedAt).toEqual(expect.any(String));

		const second = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () => puts[0].description,
			putDescription: async () => {
				throw new Error("should not write again");
			},
		});
		expect(second.captioned).toBe(0);
		expect(puts).toHaveLength(1);
	});

	it("does not write when the description already has the attribution, even without a stamp", async () => {
		const records = [{ ...run }];
		const out = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () =>
				"felt easy\r\n\r\n──\r\nFitness  +0.6\r\nGenerated by https://maxeisen.me/training\r\n──",
			putDescription: async () => {
				throw new Error("should not write when attribution is already there");
			},
		});
		expect(out.captioned).toBe(1);
		expect(records[0].captionedAt).toEqual(expect.any(String));
	});

	it("treats the older attribution line as already captioned too", async () => {
		const records = [{ ...run }];
		const out = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () => "Generated by maxeisen.me/training",
			putDescription: async () => {
				throw new Error("should not write");
			},
		});
		expect(out.captioned).toBe(1);
	});

	it("retries without the URL when Strava rejects the description", async () => {
		const puts = [];
		const records = [{ ...run }];
		const out = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () => "",
			putDescription: async (id, description) => {
				puts.push(description);
				if (description.includes("maxeisen.me/training")) {
					const err = new Error("invalid");
					err.status = 400;
					throw err;
				}
			},
		});
		expect(out.urlRejected).toBe(true);
		expect(out.captioned).toBe(1);
		expect(puts).toHaveLength(2);
		expect(puts[1]).toContain("Generated by the training dashboard");
		expect(puts[1]).not.toContain("maxeisen.me/training");
	});

	it("does not caption a ride", async () => {
		const records = [{ ...run, id: 7, sport: "ride" }];
		const out = await captionRecentRuns({
			records,
			today,
			series,
			efforts,
			getDescription: async () => {
				throw new Error("should not read a ride");
			},
			putDescription: async () => {
				throw new Error("should not write a ride");
			},
		});
		expect(out.captioned).toBe(0);
	});
});

describe("mergeActivities", () => {
	it("keeps a caption stamp across a re-shape of the same run", () => {
		const existing = [
			{ id: 1, startDateLocal: "2026-08-21T07:00:00", captionedAt: "2026-08-21T12:00:00.000Z", load: 40 },
		];
		const incoming = [{ id: 1, startDateLocal: "2026-08-21T07:00:00", load: 42 }];
		expect(mergeActivities(existing, incoming)[0]).toMatchObject({
			load: 42,
			captionedAt: "2026-08-21T12:00:00.000Z",
		});
	});
});
